### ISSUE TITLE
A few incorrect mappings in 1.14.4

### ISSUE THREAD

**Issue by gamax92** [FabricMC/intermediary#11]
There are a few entries in the mappings for 1.14.4.tiny that have the intermediary name as the official name. I searched through the list of methods and their signatures to correct the first 7, but the last two entries have the same signature so unsure.

I have not taken a look through the other mappings so these issues might exist within multiple files.

```
METHOD  cvp$a   ()Lcvp; method_21055    method_21055    doConnect
Fixed (method_21055 -> e)
METHOD  cvp$b   ()Lcvp; method_21055    method_21055    doConnect
Fixed (method_21055 -> e)
METHOD  cvp$c   ()Lcvp; method_21055    method_21055    doConnect
Fixed (method_21055 -> e)
METHOD  cvp$d   ()Lcvp; method_21055    method_21055    doConnect
Fixed (method_21055 -> e)
METHOD  cwg     (ILcwa$a;ZZ)V   method_21108    method_21108    onSlotClick
Fixed (method_21108 -> a)
METHOD  cwg     (Ljava/lang/Object;)V   method_21395    method_21395    callback
Fixed (method_21395 -> a)
METHOD  cwu     (Ljava/lang/Object;)V   method_21395    method_21395    callback
Fixed (method_21395 -> a)
METHOD  cxh$d   ()V     method_21068    method_21068    tick
METHOD  cxh$d   ()V     method_21071    method_21071    abortTask
```

**Comment by liach** [comment]
These entries are fine as I see in https://raw.githubusercontent.com/FabricMC/intermediary/master/mappings/1.14.4.tiny

This is an issue related to yarn. Mind opening an issue there and close this issue?

**Comment by gamax92** [comment]
Oh my bad
