### ISSUE TITLE
[19w37a+] Wrong intermediary name for class_1296 (PassiveEntity) subclass

### ISSUE THREAD

**Issue by liach** [FabricMC/intermediary#12]
Since 19w37a, PassiveEntity has a new subclass for entity data. However, its intermediary name is that for an anonymous class (`net/minecraft/class_1296$1`), causing some troubles in procyon and yarn. Not yet sure if this affects mods using passive entity data.

To fix this, just assign a new intermediary name to `net/minecraft/class_1296$1` like `net/minecraft/class_1296$class_4987` (dunno what the latest id is)

**Comment by modmuss50** [comment]
Nice catch, I should really add a check for this into stitch.

**Comment by modmuss50** [comment]
Fixed in 19w42a
