### ISSUE TITLE
Incorrect mappings for GlStateManager

### ISSUE THREAD

**Issue by SquidDev** [FabricMC/intermediary#4]
As of fabricmc/yarn@4ee3e576351e1dcc4201b84aa43b43bd023a8d3a, `GlStateManager.DestFactor` and `GlStateManager.SourceFactor` use their original names. However, intermediary still has them mapped to `class_*` variants, which means they must be referred to using those instead:

```
CLASS    com/mojang/blaze3d/platform/GlStateManager$DestFactor    com/mojang/blaze3d/platform/GlStateManager$class_1027
CLASS    com/mojang/blaze3d/platform/GlStateManager$SourceFactor    com/mojang/blaze3d/platform/GlStateManager$class_1033
```
(from mappings/19w03b.tiny)

I'm not sure if it'd be better to manually update the tiny files, or re-add the mappings to yarn.

**Comment by asiekierka** [comment]
We're going to do this:

* Re-add the mappings to Yarn for 19w03b,
* Remove them from Intermediary for 19w04a.

**Comment by asiekierka** [comment]
Fixed in 19w04a
