### ISSUE TITLE
Both-sided methods implementing client-only interface methods are not handled properly

### ISSUE THREAD

**Issue by Earthcomputer** [FabricMC/intermediary#6]
Hey there, not sure if this is the right repository to report this to.
We're having issues mixing into a method present on both the client and server, which on the client implements a method in an interface which is marked as `@Environment(EnvType.CLIENT)`.
Specifically, the method we're trying to mix into is `net.minecraft.server.world.ServerChunkManager#tick(java.util.function.BooleanSupplier)`, which is NOT marked `@Environment(EnvType.CLIENT)`. However, the method it implements, `net.minecraft.world.chunk.ChunkManager#tick` IS marked with that annotation.
This is leading to the release version of our mod crashing on the dedicated server.

**Comment by modmuss50** [comment]
Those seem to be 2 different methods, so their name might be clashing in yarn,

MC 1.14.3-pre1: net/minecraft/world/chunk/ChunkManager.tick
Name: a => method_12127 => tick
Descriptor: tick(Ljava/util/function/BooleanSupplier;)V
Mixin Target: net/minecraft/world/chunk/ChunkManager.tick(Ljava/util/function/BooleanSupplier;)V


MC 1.14.3-pre1: net/minecraft/server/world/ServerChunkManager.tick
Name: m => method_16155 => tick
Descriptor: tick()Z
Mixin Target: net/minecraft/server/world/ServerChunkManager.tick()Z

notice the different intermediary names.

**Comment by liach** [comment]
Notice the different method descriptors (`(Ljava/util/function/BooleanSupplier;)V` and `()Z`) as well.

**Comment by Earthcomputer** [comment]
@modmuss50 there are two different methods called "tick" in ServerChunkManager. You want the one which takes a BooleanSupplier ;)

**Comment by Runemoro** [comment]
A two-side method can override a client-side method through a client-side bridge.

**Comment by gnembon** [comment]
Just to clarify: These mixins work on client in dev environment and released as a mod. It DOES work on dev when run as a server, but does NOT work when attempted to run a server from a distributed mod jar.

**Comment by flori-schwa** [comment]
I am experiencing the same issue with the same method in 1.15.2: flori-schwa/VarLightFabric#2

[The Mixin that is failing to apply](https://github.com/flori-schwa/VarLightFabric/blob/1.1/src/main/java/me/shawlaf/varlight/fabric/mixin/ServerChunkManagerMixin.java)

**Comment by magneticflux-** [comment]
Am I correct in the assumption that this the section which needs to be fixed to remap the server jar properly?https://github.com/FabricMC/stitch/blob/57b0e7fe30e4d7768b26f610385434771e90aad3/src/main/java/net/fabricmc/stitch/merge/JarMerger.java#L185

Or is it this section?
https://github.com/FabricMC/stitch/blob/57b0e7fe30e4d7768b26f610385434771e90aad3/src/main/java/net/fabricmc/stitch/merge/ClassMerger.java#L64

**Comment by modmuss50** [comment]
As far as I know its not an issue with jar merging, ita a bug with stitch's class propagation not taking into account method access.

**Comment by modmuss50** [comment]
Going to close this issue as it will no longer be an issue going forward into 1.17, this seems to be causing little issue right now so its not worth the very delicate effort of fixing past versions.
