### ISSUE TITLE
[19w34a] com/mojang/blaze3d/platform/TextureUtil lacking an intermediary name

### ISSUE THREAD

**Issue by liach** [FabricMC/intermediary#9]
Back in 1.14.4, this TextureUtil class was not obfuscated. Now, it is obfuscated and becomes `cvy`.

For some reason, this class lacks an intermediary name. In the built yarn tiny file, its intermediary name is just `com/mojang/blaze3d/platform/TextureUtil`, same as its yarn name.

This issue is urgent: since it has a package-level access (calls `net/minecraft/client/texture/NativeImage$GLFormat.getGlConstant()I` which is package-private, or `cvu$b.a()I`), this causes illegal access exceptions when running intermediary-named fabric client for 19w34a.

Example crash report: https://gist.github.com/def790af56fe52fa66fb5941617bbcc4

**Comment by modmuss50** [comment]
Fixed with: https://github.com/FabricMC/intermediary/commit/65f9a34744151b6cd802c6f0394c30dab4376727
